preset: psr12

enabled:
  - no_extra_consecutive_blank_lines
  - short_array_syntax
  - method_separation
  - multiline_array_trailing_comma
  - no_empty_lines_after_phpdocs
  - operators_spaces
  - length_ordered_imports
  - phpdoc_align
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - blank_line_before_return
  - no_short_bool_cast
  - single_quote
  - space_after_semicolon
  - cast_spaces
  - standardize_not_equals
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operators_spaces
  - unneeded_control_parentheses
  - no_unused_imports
